FROM java:8
VOLUME /tmp
ADD springboot-app /springboot-app
WORKDIR /springboot-app
RUN ./gradlew build
RUN sh -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
